package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

func main() {
	output := flag.String("output", "", "CSS output path")
	flag.Parse()
	if *output == "" {
		fmt.Fprintln(os.Stderr, "stylegen: -output is required")
		os.Exit(2)
	}

	formatter := chromahtml.New(
		chromahtml.WithClasses(true),
		chromahtml.WithAllClasses(true),
		chromahtml.WithCSSComments(false),
	)
	themes := []struct {
		scheme string
		name   string
		extra  string
	}{
		{scheme: "light", name: "catppuccin-latte"},
		{
			scheme: "dark",
			name:   "catppuccin-frappe",
			// Frappe's stock comments are intentionally very subdued (2.87:1
			// against its background). Keep them muted while meeting 4.5:1
			// text contrast.
			extra: ".chroma .c, .chroma .ch, .chroma .cm, .chroma .c1, .chroma .cs, .chroma .cp, .chroma .cpf { color: #949cbb; }\n",
		},
	}

	var css bytes.Buffer
	css.WriteString("/* Code generated by go generate ./internal/mdhighlight; DO NOT EDIT. */\n")
	css.WriteString(".chroma { color: var(--text); background-color: var(--code); }\n")
	for _, theme := range themes {
		style := styles.Get(theme.name)
		if style == nil {
			fmt.Fprintf(os.Stderr, "stylegen: unknown Chroma style %q\n", theme.name)
			os.Exit(1)
		}
		var rules bytes.Buffer
		if err := formatter.WriteCSS(&rules, style); err != nil {
			fmt.Fprintf(os.Stderr, "stylegen: generate %s CSS: %v\n", theme.scheme, err)
			os.Exit(1)
		}
		rules.WriteString(theme.extra)
		// The light rules are the default. The dark rules apply when the system
		// prefers dark and the page has not been forced light, or when the page
		// has been forced dark (see the theme toggle in app.js); nesting keeps a
		// single copy of the rules per wrapper.
		if theme.scheme == "light" {
			css.WriteString("\n")
			css.Write(rules.Bytes())
			continue
		}
		for _, wrapper := range []struct{ open, close string }{
			{"@media (prefers-color-scheme: dark) {\n:root:not([data-theme=\"light\"]) {\n", "}\n}\n"},
			{":root[data-theme=\"dark\"] {\n", "}\n"},
		} {
			css.WriteString("\n" + wrapper.open)
			css.Write(rules.Bytes())
			css.WriteString(wrapper.close)
		}
	}

	if err := os.WriteFile(*output, css.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "stylegen: write CSS: %v\n", err)
		os.Exit(1)
	}
}
