package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

func main() {
	output := flag.String("output", "", "CSS output path")
	flag.Parse()
	if *output == "" {
		fmt.Fprintln(os.Stderr, "stylegen: -output is required")
		os.Exit(2)
	}

	formatter := chromahtml.New(
		chromahtml.WithClasses(true),
		chromahtml.WithAllClasses(true),
		chromahtml.WithCSSComments(false),
	)
	themes := []struct {
		scheme string
		name   string
		extra  string
	}{
		{scheme: "light", name: "catppuccin-latte"},
		{
			scheme: "dark",
			name:   "catppuccin-frappe",
			// Frappe's stock comments are intentionally very subdued (2.87:1
			// against its background). Keep them muted while meeting 4.5:1
			// text contrast.
			extra: ".chroma .c, .chroma .ch, .chroma .cm, .chroma .c1, .chroma .cs, .chroma .cp, .chroma .cpf { color: #949cbb; }\n",
		},
	}

	var css bytes.Buffer
	css.WriteString("/* Code generated by go generate ./internal/mdhighlight; DO NOT EDIT. */\n")
	css.WriteString(".chroma { color: var(--text); background-color: var(--code); }\n")
	for _, theme := range themes {
		style := styles.Get(theme.name)
		if style == nil {
			fmt.Fprintf(os.Stderr, "stylegen: unknown Chroma style %q\n", theme.name)
			os.Exit(1)
		}
		fmt.Fprintf(&css, "\n@media (prefers-color-scheme: %s) {\n", theme.scheme)
		if err := formatter.WriteCSS(&css, style); err != nil {
			fmt.Fprintf(os.Stderr, "stylegen: generate %s CSS: %v\n", theme.scheme, err)
			os.Exit(1)
		}
		css.WriteString(theme.extra)
		css.WriteString("}\n")
	}

	if err := os.WriteFile(*output, css.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "stylegen: write CSS: %v\n", err)
		os.Exit(1)
	}
}
